### ISSUE TITLE
Could I have you email?

### ISSUE THREAD

**Issue by littleggghost** [dicarlo236/mpc-solver#1]
Hi, Jared Di Carlo
I'm Trivas. Sorry for this issue because this is the only way I can contact with you. I did't find your email at your blog or thesis.
I see your great job of mini cheetah on Youtube. That was amazing. I can't imagine that a mechanical quadruped could perform much better than a real dog. And I want to know the control principle under the video.
Then I read your two theses about MPC control and I want to consult two question.
I think discuss in here is out of this repository, so I just want to have your email first.
Please forgive me this issue again.

Best Regards
Trivas Zhang

**Comment by dicarlo236** [comment]
Hi Trivas,
Thanks for the interest!  My email is dicarloj@mit.edu.

-Jared

**Comment by littleggghost** [comment]
Really thanks for your rapidly reply! It’s my honour to communicate with you!
